version: "3.9"

services:
  webapp:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    image: wevote-webapp:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "development"   # change to production in prod
      DISABLE_WDS_OVERLAY: "1" # disable linter errors overlay for webpack
      SERVE_STORYBOOK_STATIC: "1"   # only for storybook in this dev container
    volumes:
      - .:/usr/src/app        # optional: for live dev
      - /usr/src/app/node_modules
    command: npm start -- --host 0.0.0.0       # for production build you might serve build folder
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app
          initial_sync: true
          ignore:
            - node_modules
            - package.json
            - package-lock.json